language: python
python:
  - "3.7"
install: pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: FplthdZBIMV4uccxrV5BUmPnnsDjkUCEdDr5yqjPqMT7mWJdOjEYAt+pL2lg7LxLYc2PVseS9a4GG/5rKGvkK3JER3yMqAt9zCNJJK1XHH26xWQ2wz6XjHCnybBIT9yWkaHdsLC0bgveAIxUoOvF7nBI4pUZGyX0YemwSfDfdcvKA6kba4FQiK2T7J04zuKpo+74rGsJM7dlAT7Nva+wZok7/R/BtXRJgmdBqPfD3ofTAOnJkW3Czvw3fbgTIOj9zJ9TIh0hBOAdVgA8ZF4HXRZ8fTdABepl2pJeDX0FLOyoz1awPzAhjyMerhavJ4HfQ9xuw/y7ERvWvHYFRqgFO5EgqmNd1mJFhTMltJofiUWycXupwfGdvm+sXSRh2kRaIKHIacfxazcVparFkCmVebVyVzui+67GOXjzlYHxc98631qHNczQpJ9bg9fedaDsPnp9eZc8bOd6Y30QzDaNWAk+7PzfnwTMWXunGmZDZBx//NGK1OxzgH14jISY/UDtRtAaRiTEzL/i7qhFNh/YJEU3n5t/glAFl6TfKM4MdRZBwZXA/pVmvDhd85fto6fnKRzf7sF1SZ9kZcJAkWHwYwlYiwdPitIwTLKw+ysZRH0KVIAxzFTbzSwqZQwbS0htr/IqKWNLOIgvuCbGqH/HlPeFycf2N1P3ZHk9gWqtNf0=
  distributions: sdist bdist_wheel
  skip_existing: true
